import Providers from "@/app/providers";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: "Engetak",
  description: "Generated by Joao Nishimoto",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {props.children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
